# Generated by Django 4.2.7 on 2026-05-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Volunteer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("community_health_worker", "Community Health Worker"),
                            ("nurse", "Nurse"),
                            ("doctor", "Doctor"),
                            ("counselor", "Counselor"),
                            ("data_entry", "Data Entry Clerk"),
                            ("driver", "Driver"),
                            ("coordinator", "Field Coordinator"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("on_leave", "On Leave"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200)),
                ("tasks_completed", models.PositiveIntegerField(default=0)),
                ("joined_date", models.DateField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
