# Generated by Django 4.2.7 on 2026-05-15 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("coordinator", "Outreach Coordinator"),
                            ("healthcare_worker", "Healthcare Worker"),
                            ("volunteer", "Volunteer"),
                            ("data_manager", "Data Manager"),
                        ],
                        default="healthcare_worker",
                        max_length=30,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("avatar_initials", models.CharField(blank=True, max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
