# Generated by Django 5.1.15 on 2026-05-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("system_administrator", "System Administrator"),
                    ("coordinator", "Outreach Coordinator"),
                    ("healthcare_worker", "Healthcare Worker"),
                    ("volunteer", "Volunteer"),
                    ("admin", "Administrator"),
                ],
                default="healthcare_worker",
                max_length=30,
            ),
        ),
    ]
