# Generated by Django 5.1.15 on 2026-05-15 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="screening",
            options={"ordering": ["-screening_date", "-created_at"]},
        ),
        migrations.AddField(
            model_name="screening",
            name="comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="screening",
            name="followup_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="screening",
            name="next_followup_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screening",
            name="recommendations",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="screening",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("referred", "Referred"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="screening",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="screenings_performed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="screening",
            name="result",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="screening",
            name="screening_type",
            field=models.CharField(
                choices=[
                    ("hiv", "HIV"),
                    ("malaria", "Malaria"),
                    ("tuberculosis_tb", "Tuberculosis (TB)"),
                    ("diabetes", "Diabetes"),
                    ("hypertension", "Hypertension"),
                    ("pregnancy_test", "Pregnancy Test"),
                    ("cervical_cancer", "Cervical Cancer"),
                    ("breast_cancer", "Breast Cancer"),
                    ("bmi_nutrition", "BMI / Nutrition"),
                    ("mental_health", "Mental Health"),
                    ("hepatitis_b", "Hepatitis B"),
                    ("hepatitis_c", "Hepatitis C"),
                    ("sti_screening", "STI Screening"),
                    ("cholesterol", "Cholesterol"),
                    ("sickle_cell", "Sickle Cell"),
                    ("vision_screening", "Vision Screening"),
                    ("hearing_screening", "Hearing Screening"),
                    ("covid_19", "COVID-19"),
                    ("urinalysis", "Urinalysis"),
                    ("blood_group", "Blood Group"),
                    ("anemia", "Anemia"),
                    ("child_malnutrition", "Child Malnutrition"),
                    ("family_planning", "Family Planning"),
                    ("maternal_risk_assessment", "Maternal Risk Assessment"),
                    ("other", "Other"),
                ],
                max_length=100,
            ),
        ),
    ]
