# Generated by Django 5.1.15 on 2026-05-15 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
        ("patients", "0002_screening_expanded_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="address_text",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="patient",
            name="cell",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="locations.cell",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="locations.country",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="locations.district",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="province",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="locations.province",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="sector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="locations.sector",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="village",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="locations.village",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="location",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=models.CharField(max_length=30),
        ),
    ]
